# SPDX-License-Identifier: GPL-2.0
#
# Avalon DMA driver
#
# Author: Alexander Gordeev <a.gordeev.box@gmail.com>
#
obj-$(CONFIG_AVALON_DRV)	+= avalon-drv.o

avalon-drv-objs :=	avalon-drv-dev.o \
			avalon-drv-ioctl.o \
			avalon-drv-mmap.o \
			avalon-drv-sg-buf.o \
			avalon-drv-xfer.o \
			avalon-drv-util.o
