# SPDX-License-Identifier: GPL-2.0
#
# Avalon DMA driver
#
# Copyright (C) 2018-2019 DAQRI, http://www.daqri.com/
#
# Created by Alexander Gordeev <alexander.gordeev@daqri.com>
#
# This file is subject to the terms and conditions of the GNU General
# Public License. See the file COPYING in the main directory of the
# Linux distribution for more details.
#
obj-$(CONFIG_AVALON_DRV)	+= avalon-drv.o

avalon-drv-objs :=	avalon-drv-dev.o \
			avalon-drv-ioctl.o \
			avalon-drv-mmap.o \
			avalon-drv-sg-buf.o \
			avalon-drv-xfer.o \
			avalon-drv-util.o \
			avalon-drv-attr.o
