# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019, The Linux Foundation. All rights reserved.
# Author: Alexander Gordeev <a.gordeev.box@gmail.com>
#
# Avalon DMA engine
#
obj-$(CONFIG_AVALON_DMA)	+= avalon-dma.o

avalon-dma-objs			:= avalon-hw.o \
				   avalon-core.o \
				   avalon-pci.o
