obj-$(CONFIG_AVALON_DMA_ENG)	+= avalon-dma-eng.o
obj-$(CONFIG_AVALON_DMA_DRV)	+= avalon-dma-drv.o

avalon-dma-eng-objs :=	avalon-dma.o \
			avalon-dma-util.o \
			avalon-dma-stats.o \
			avalon-dma-interrupt.o

avalon-dma-drv-objs :=	avalon-drv-core.o \
			avalon-drv-fops.o \
			avalon-drv-util.o \
			avalon-drv-attr.o \
			avalon-drv-interrupt.o
