# SPDX-License-Identifier: GPL-2.0
#
# Avalon DMA engine
#
# Copyright (C) 2018-2019 DAQRI, http://www.daqri.com/
#
# Created by Alexander Gordeev <alexander.gordeev@daqri.com>
#
# This file is subject to the terms and conditions of the GNU General
# Public License. See the file COPYING in the main directory of the
# Linux distribution for more details.
#
obj-$(CONFIG_AVALON_DMA)	+= avalon-dma.o

avalon-dma-objs :=	avalon-dma-core.o \
			avalon-dma-util.o \
			avalon-dma-interrupt.o
