# SPDX-License-Identifier: GPL-2.0
#
# Avalon DMA engine
#
# Author: Alexander Gordeev <a.gordeev.box@gmail.com>
#
obj-$(CONFIG_AVALON_DMA)	+= avalon-dma.o

avalon-dma-objs :=	avalon-dma-core.o \
			avalon-dma-util.o \
			avalon-dma-interrupt.o
