# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019, The Linux Foundation. All rights reserved.
# Author: Alexander Gordeev <a.gordeev.box@gmail.com>
#
# Avalon DMA driver
#
obj-$(CONFIG_AVALON_TEST)	+= avalon-test.o

avalon-test-objs :=	avalon-dev.o \
			avalon-ioctl.o \
			avalon-mmap.o \
			avalon-sg-buf.o \
			avalon-xfer.o
